version: "3.7"

services:
  dashbaoard:
    image: "nginx:latest"
    container_name: "dashbaoard"
    restart: "unless-stopped"
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    ports:
      - 80:80
